### ISSUE TITLE
Mobile Storefront - Refactor mobile-htmlhead-include

### ISSUE THREAD

**Issue by jj-lucas** [jackjonesfashion/tasks#117] opened 2015-05-22 07:06 UTC
There's some messy inline styling on the mobile htmlhead include (we have an xml import for that)..
Please refactor it and plug it where most appropriate.

![image](https://cloud.githubusercontent.com/assets/2851890/7765745/d1f169b2-0061-11e5-85eb-edf862fdc396.png)

**Comment by jeppeolesen** [comment] 2015-05-22 08:30
This is a duplicate of #85 

Closed

**Closed by jeppeolesen** 2015-05-22 08:30 UTC
Labels: Enhancement, Priority: Low
