### ISSUE TITLE
Sentence is double layered

### ISSUE THREAD

**Issue by jj-marie** [jackjonesfashion/tasks#137] opened 2015-06-10 06:16 UTC
![capture](https://cloud.githubusercontent.com/assets/12825139/8076107/ef0f7b7e-0f48-11e5-9d3d-eae775ec66be.JPG)

**Comment by jj-lucas** [comment] 2015-06-10 06:33
Closing, duplicate of #136

**Closed by jj-lucas** 2015-06-10 06:33 UTC
Labels: Duplicate
